sequenceDiagram

    participant Agent_1

    participant Agent_2

    participant Controller

    participant OEF



    activate Controller

    Agent_1->>Agent_1: (1) get_service_description()
    Agent_1->>OEF: (2) register_service(description)

    Agent_2->>Agent_2: (3) get_service_description()
    Agent_2->>OEF: (4) register_service(description)

    Agent_1->>Agent_1: (5) build_services_query()
    Agent_1->>OEF: (6) search_services(query)

    OEF->>Agent_1: (7) search_results(agents)

    Agent_1->>Agent_2: (8) send_cfp(1, 1, "agent_2_pbk", 0, query)
    Agent_2->>Agent_2: (9) get_proposal()

    Agent_2->>Agent_1: (10) send_propose(2, 1, "agent_1_pbk", 1, proposals)

    Agent_1->>Agent_2: (11) send_accept(3, 1, "agent_2_pbk", 2)

    Agent_2->>Agent_1: (13) send_accept(4, 1, "agent_1_pbk", 3)
    Agent_2->>Controller: (14) send_message(4, 1, "controller_pbk", transaction)

    Agent_1->>Controller: (12) send_message(5, 1, "controller_pbk", transaction)

    Controller->>Agent_1: (15) TransactionConfirmation(transaction)
    Controller->>Agent_2: (16) TransactionConfirmation(transaction)

    deactivate Controller
