sequenceDiagram
	participant Agent_1
    participant Agent_2
    participant Controller

    activate Controller
    Agent_1->>Agent_2: send_cfp(msg_id: 1, dialogue_id: 1, destination: agent_2_pbk, target: 0, query=Query)
    Agent_2->>Agent_1: send_decline(msg_id: 2, dialogue_id: 1, destination: agent_1_pbk, target: 1)
    deactivate Controller