sequenceDiagram
    participant OEF
    participant Controller

    Note right of Controller: register as a controller agent.

    Controller->>OEF: register_service("tac", Description{version=VERSION_ID})
    Controller->>Controller: run()
    activate Controller
    deactivate Controller

    Note right of Controller: Waiting for 'REGISTER' messages from TAC agents, until 'start time'.