#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""Parse game data generated by the examples."""

import argparse
import json
import pprint
from typing import Dict, Any

from tac.core import Game


def parse_arguments():
    parser = argparse.ArgumentParser("parse_data", description="Parse a data dump.")

    parser.add_argument("filepath", type=str, help="The path to the file of the experiment (JSON).")
    return parser.parse_args()


def read_data(filepath: str) -> Dict[str, Any]:
    with open(filepath) as f:
        data = json.load(f)

    return data


if __name__ == '__main__':
    arguments = parse_arguments()
    filepath = arguments.filepath

    data = read_data(filepath)
    game = Game.from_dict(data)

    pprint.pprint(data)
    for g in game.game_states:
        print(str(g))
